
apiVersion: v1
kind: Secret
metadata:
  name: exam-client-jwt
  namespace: kafka
  labels:
    konghq.com/credential: jwt  # Questo label dice a Kong: "Questa è una credenziale"
type: Opaque
stringData:
  # Nota: Niente JSON stringificato strano, usiamo chiavi dirette
  key: "exam-client-key"        # Deve combaciare con il claim 'iss' del tuo token Python
  algorithm: "HS256"            # Deve combaciare con il tuo script Python
  secret: "supersecret"         # La tua stringa segreta
  rsa_public_key: ""            # Vuoto perché usi HS256 (simmetrico)