apiVersion: v1
kind: Secret
metadata:
  name: exam-client-jwt
  namespace: kafka
  labels:
    konghq.com/credential: jwt
type: Opaque
stringData:
  key: "exam-client-key"
  algorithm: "HS256"
  secret: "supersecret"