apiVersion: v1
kind: Secret
metadata:
  name: exam-client-jwt
  namespace: kafka
  labels:
    konghq.com/credential: jwt   # tipo di credenziale per Kong
type: Opaque
stringData:
  kongCredType: jwt              # ancora richiesto da alcune versioni del webhook
  key: exam-client-key           # ⬅️ deve coincidere con iss del token
  secret: supersecret            # ⬅️ deve coincidere con la secret Python
  algorithm: HS256               # ⬅️ deve coincidere con jwt.encode(...)
