# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: metrics-ingress
#   namespace: metrics
#   annotations:
#     konghq.com/plugins: cors-plugin,jwt-auth
# spec:
#   ingressClassName: kong
#   rules:
#     - host: metrics.192.168.49.2.nip.io
#       http:
#         paths:
#           - path: /metrics
#             pathType: Prefix
#             backend:
#               service:
#                 name: metrics-service
#                 port:
#                   number: 5001
#           # AGGIUNTA: Permetti il passaggio anche per healthz
#           - path: /healthz
#             pathType: Prefix
#             backend:
#               service:
#                 name: metrics-service
#                 port:
#                   number: 5001

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: metrics-ingress
  namespace: metrics
  annotations:
    # Qui elenchiamo i plugin attivi. Nota: rate-limiting lo aggiungeremo dopo se vuoi.
    konghq.com/plugins: cors-plugin,jwt-auth, global-rate-limit
    # IMPORTANTE: Non rimuovere il path. Il servizio Flask si aspetta "/healthz", non "/"
    konghq.com/strip-path: "false"
spec:
  ingressClassName: kong
  rules:
    - host: metrics.192.168.49.2.nip.io
      http:
        paths:
          # CATTURA TUTTO: Qualsiasi cosa arrivi su questo host, mandala al servizio.
          - path: /
            pathType: Prefix
            backend:
              service:
                name: metrics-service
                port:
                  number: 5001