apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: student-events
  namespace: kafka
  labels:
    strimzi.io/cluster: uni-it-cluster
spec:
  partitions: 3
  replicas: 2  # 2 --> se un broker muore, l'altro ha i dati
  config:
    retention.ms: 604800000
    segment.bytes: 1073741824
    min.insync.replicas: 1 